CREATE TABLE IF NOT EXISTS fighter_momentum (
    fighter_id UUID PRIMARY KEY REFERENCES fighters(id) ON DELETE CASCADE,
    current_value DOUBLE PRECISION DEFAULT 0,
    last_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
